name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: List repository files
        run: |
          ls -lah
          echo "Current working directory: $(pwd)"

      - name: List regipy_tests directory
        run: |
          ls -lah regipy_tests
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pylint

      - name: Lint with pylint
        run: |
          pylint regipy --output-format=text
        # Temp. allow continuing on lint errors
        continue-on-error: true

      - name: CLI Tests
        run: |
          pytest -v regipy_tests/cli_tests.py
        # Temp. allow failure due to inconsistency between CI env and local env.
        continue-on-error: true
        working-directory: ${{ github.workspace }}

      - name: Check plugin_tests.py existence
        run: |
          if [ -f regipy_tests/plugin_tests.py ]; then
            echo "plugin_tests.py exists"
          else
            echo "plugin_tests.py does not exist"
          fi
        working-directory: ${{ github.workspace }}

      - name: Plugin Tests
        run: |
          pytest -v regipy_tests/plugin_tests.py
        working-directory: ${{ github.workspace }}

      - name: Library Tests
        run: |
          pytest -v regipy_tests/tests.py
        working-directory: ${{ github.workspace }}